# Dictionary grouped by continent (America split into North/Central/South) -> country code -> list of tz identifiers
# Source: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# Note: 'Central America' here includes the Central American isthmus AND Caribbean island nations/territories

timezones = {
    'Africa': {
        'AO': ['Africa/Lagos', 'Africa/Luanda'],
        'BF': ['Africa/Abidjan', 'Africa/Ouagadougou'],
        'BI': ['Africa/Bujumbura', 'Africa/Maputo'],
        'BJ': ['Africa/Lagos', 'Africa/Porto-Novo'],
        'BW': ['Africa/Gaborone', 'Africa/Maputo'],
        'CD': ['Africa/Kinshasa', 'Africa/Lagos', 'Africa/Lubumbashi', 'Africa/Maputo'],
        'CF': ['Africa/Bangui', 'Africa/Lagos'],
        'CG': ['Africa/Brazzaville', 'Africa/Lagos'],
        'CI': ['Africa/Abidjan'],
        'CM': ['Africa/Douala', 'Africa/Lagos'],
        'DJ': ['Africa/Djibouti', 'Africa/Nairobi'],
        'DZ': ['Africa/Algiers'],
        'EG': ['Africa/Cairo', 'Egypt'],
        'EH': ['Africa/El_Aaiun'],
        'ER': ['Africa/Asmara', 'Africa/Asmera', 'Africa/Nairobi'],
        'ES': ['Africa/Ceuta'],
        'ET': ['Africa/Addis_Ababa', 'Africa/Nairobi'],
        'GA': ['Africa/Lagos', 'Africa/Libreville'],
        'GH': ['Africa/Abidjan', 'Africa/Accra'],
        'GM': ['Africa/Abidjan', 'Africa/Banjul'],
        'GN': ['Africa/Abidjan', 'Africa/Conakry'],
        'GQ': ['Africa/Lagos', 'Africa/Malabo'],
        'GW': ['Africa/Bissau'],
        'IS': ['Africa/Abidjan'],
        'KE': ['Africa/Nairobi'],
        'KM': ['Africa/Nairobi'],
        'LR': ['Africa/Monrovia'],
        'LS': ['Africa/Johannesburg', 'Africa/Maseru'],
        'LY': ['Africa/Tripoli', 'Libya'],
        'MA': ['Africa/Casablanca'],
        'MG': ['Africa/Nairobi'],
        'ML': ['Africa/Abidjan', 'Africa/Bamako', 'Africa/Timbuktu'],
        'MR': ['Africa/Abidjan', 'Africa/Nouakchott'],
        'MW': ['Africa/Blantyre', 'Africa/Maputo'],
        'MZ': ['Africa/Maputo'],
        'NA': ['Africa/Windhoek'],
        'NE': ['Africa/Lagos', 'Africa/Niamey'],
        'NG': ['Africa/Lagos'],
        'RW': ['Africa/Kigali', 'Africa/Maputo'],
        'SD': ['Africa/Khartoum'],
        'SH': ['Africa/Abidjan'],
        'SL': ['Africa/Abidjan', 'Africa/Freetown'],
        'SN': ['Africa/Abidjan', 'Africa/Dakar'],
        'SO': ['Africa/Mogadishu', 'Africa/Nairobi'],
        'SS': ['Africa/Juba'],
        'ST': ['Africa/Sao_Tome'],
        'SZ': ['Africa/Johannesburg', 'Africa/Mbabane'],
        'TD': ['Africa/Ndjamena'],
        'TG': ['Africa/Abidjan', 'Africa/Lome'],
        'TN': ['Africa/Tunis'],
        'TZ': ['Africa/Dar_es_Salaam', 'Africa/Nairobi'],
        'UG': ['Africa/Kampala', 'Africa/Nairobi'],
        'YT': ['Africa/Nairobi'],
        'ZA': ['Africa/Johannesburg'],
        'ZM': ['Africa/Lusaka', 'Africa/Maputo'],
        'ZW': ['Africa/Harare', 'Africa/Maputo'],
    },
    'Antarctica': {
        'AQ': [
            'Antarctica/Casey',
            'Antarctica/Davis',
            'Antarctica/DumontDUrville',
            'Antarctica/Mawson',
            'Antarctica/McMurdo',
            'Antarctica/Palmer',
            'Antarctica/Rothera',
            'Antarctica/South_Pole',
            'Antarctica/Syowa',
            'Antarctica/Troll',
            'Antarctica/Vostok',
        ],
        'AU': ['Antarctica/Macquarie'],
    },
    'Asia': {
        'AE': ['Asia/Dubai'],
        'AF': ['Asia/Kabul'],
        'AM': ['Asia/Yerevan'],
        'AQ': ['Asia/Riyadh', 'Asia/Singapore'],
        'AU': ['Asia/Tokyo'],
        'AZ': ['Asia/Baku'],
        'BD': ['Asia/Dacca', 'Asia/Dhaka'],
        'BH': ['Asia/Bahrain', 'Asia/Qatar'],
        'BN': ['Asia/Brunei', 'Asia/Kuching'],
        'BT': ['Asia/Thimbu', 'Asia/Thimphu'],
        'CC': ['Asia/Yangon'],
        'CN': [
            'Asia/Chongqing',
            'Asia/Chungking',
            'Asia/Harbin',
            'Asia/Kashgar',
            'Asia/Shanghai',
            'Asia/Urumqi',
            'PRC',
        ],
        'CX': ['Asia/Bangkok'],
        'CY': ['Asia/Famagusta', 'Asia/Nicosia'],
        'GE': ['Asia/Tbilisi'],
        'HK': ['Asia/Hong_Kong', 'Hongkong'],
        'ID': [
            'Asia/Jakarta',
            'Asia/Jayapura',
            'Asia/Makassar',
            'Asia/Pontianak',
            'Asia/Ujung_Pandang',
        ],
        'IL': ['Asia/Jerusalem', 'Asia/Tel_Aviv', 'Israel'],
        'IN': ['Asia/Calcutta', 'Asia/Kolkata'],
        'IQ': ['Asia/Baghdad'],
        'IR': ['Asia/Tehran', 'Iran'],
        'JO': ['Asia/Amman'],
        'JP': ['Asia/Tokyo', 'Japan'],
        'KG': ['Asia/Bishkek'],
        'KH': ['Asia/Bangkok', 'Asia/Phnom_Penh'],
        'KP': ['Asia/Pyongyang'],
        'KR': ['Asia/Seoul', 'ROK'],
        'KW': ['Asia/Kuwait', 'Asia/Riyadh'],
        'KZ': [
            'Asia/Almaty',
            'Asia/Aqtau',
            'Asia/Aqtobe',
            'Asia/Atyrau',
            'Asia/Oral',
            'Asia/Qostanay',
            'Asia/Qyzylorda',
        ],
        'LA': ['Asia/Bangkok', 'Asia/Vientiane'],
        'LB': ['Asia/Beirut'],
        'LK': ['Asia/Colombo'],
        'MM': ['Asia/Rangoon', 'Asia/Yangon'],
        'MN': ['Asia/Choibalsan', 'Asia/Hovd', 'Asia/Ulaanbaatar', 'Asia/Ulan_Bator'],
        'MO': ['Asia/Macao', 'Asia/Macau'],
        'MY': ['Asia/Kuala_Lumpur', 'Asia/Kuching', 'Asia/Singapore'],
        'NP': ['Asia/Kathmandu', 'Asia/Katmandu'],
        'OM': ['Asia/Dubai', 'Asia/Muscat'],
        'PH': ['Asia/Manila'],
        'PK': ['Asia/Karachi'],
        'PS': ['Asia/Gaza', 'Asia/Hebron'],
        'QA': ['Asia/Qatar'],
        'RE': ['Asia/Dubai'],
        'RU': [
            'Asia/Anadyr',
            'Asia/Barnaul',
            'Asia/Chita',
            'Asia/Irkutsk',
            'Asia/Kamchatka',
            'Asia/Khandyga',
            'Asia/Krasnoyarsk',
            'Asia/Magadan',
            'Asia/Novokuznetsk',
            'Asia/Novosibirsk',
            'Asia/Omsk',
            'Asia/Sakhalin',
            'Asia/Srednekolymsk',
            'Asia/Tomsk',
            'Asia/Ust-Nera',
            'Asia/Vladivostok',
            'Asia/Yakutsk',
            'Asia/Yekaterinburg',
        ],
        'SA': ['Asia/Riyadh'],
        'SC': ['Asia/Dubai'],
        'SG': ['Asia/Singapore', 'Singapore'],
        'SY': ['Asia/Damascus'],
        'TF': ['Asia/Dubai'],
        'TH': ['Asia/Bangkok'],
        'TJ': ['Asia/Dushanbe'],
        'TL': ['Asia/Dili'],
        'TM': ['Asia/Ashgabat', 'Asia/Ashkhabad'],
        'TR': ['Asia/Istanbul'],
        'TW': ['Asia/Taipei', 'ROC'],
        'UZ': ['Asia/Samarkand', 'Asia/Tashkent'],
        'VN': ['Asia/Bangkok', 'Asia/Ho_Chi_Minh', 'Asia/Saigon'],
        'YE': ['Asia/Aden', 'Asia/Riyadh'],
    },
    'Atlantic': {
        'BM': ['Atlantic/Bermuda'],
        'CV': ['Atlantic/Cape_Verde'],
        'ES': ['Atlantic/Canary'],
        'FK': ['Atlantic/Stanley'],
        'FO': ['Atlantic/Faeroe', 'Atlantic/Faroe'],
        'GS': ['Atlantic/South_Georgia'],
        'IS': ['Atlantic/Reykjavik', 'Iceland'],
        'PT': ['Atlantic/Azores', 'Atlantic/Madeira'],
        'SH': ['Atlantic/St_Helena'],
        'SJ': ['Atlantic/Jan_Mayen'],
    },
    'Australia': {
        'AU': [
            'Australia/ACT',
            'Australia/Adelaide',
            'Australia/Brisbane',
            'Australia/Broken_Hill',
            'Australia/Canberra',
            'Australia/Currie',
            'Australia/Darwin',
            'Australia/Eucla',
            'Australia/Hobart',
            'Australia/LHI',
            'Australia/Lindeman',
            'Australia/Lord_Howe',
            'Australia/Melbourne',
            'Australia/North',
            'Australia/NSW',
            'Australia/Perth',
            'Australia/Queensland',
            'Australia/South',
            'Australia/Sydney',
            'Australia/Tasmania',
            'Australia/Victoria',
            'Australia/West',
            'Australia/Yancowinna',
        ]
    },
    'Central America': {
        'AG': ['America/Antigua', 'America/Puerto_Rico'],
        'AI': ['America/Anguilla', 'America/Puerto_Rico'],
        'AW': ['America/Aruba', 'America/Puerto_Rico'],
        'BB': ['America/Barbados'],
        'BL': ['America/Puerto_Rico', 'America/St_Barthelemy'],
        'BQ': ['America/Kralendijk', 'America/Puerto_Rico'],
        'BS': ['America/Nassau', 'America/Toronto'],
        'BZ': ['America/Belize'],
        'CR': ['America/Costa_Rica'],
        'CU': ['America/Havana', 'Cuba'],
        'CW': ['America/Curacao', 'America/Puerto_Rico'],
        'DM': ['America/Dominica', 'America/Puerto_Rico'],
        'DO': ['America/Santo_Domingo'],
        'GD': ['America/Grenada', 'America/Puerto_Rico'],
        'GP': ['America/Guadeloupe', 'America/Puerto_Rico'],
        'GT': ['America/Guatemala'],
        'HN': ['America/Tegucigalpa'],
        'HT': ['America/Port-au-Prince'],
        'JM': ['America/Jamaica', 'Jamaica'],
        'KN': ['America/Puerto_Rico', 'America/St_Kitts'],
        'KY': ['America/Cayman', 'America/Panama'],
        'LC': ['America/Puerto_Rico', 'America/St_Lucia'],
        'MF': ['America/Marigot', 'America/Puerto_Rico'],
        'MQ': ['America/Martinique'],
        'MS': ['America/Montserrat', 'America/Puerto_Rico'],
        'NI': ['America/Managua'],
        'PA': ['America/Panama'],
        'PR': ['America/Puerto_Rico'],
        'SV': ['America/El_Salvador'],
        'SX': ['America/Lower_Princes', 'America/Puerto_Rico'],
        'TC': ['America/Grand_Turk'],
        'TT': ['America/Port_of_Spain', 'America/Puerto_Rico'],
        'VC': ['America/Puerto_Rico', 'America/St_Vincent'],
        'VG': ['America/Puerto_Rico', 'America/Tortola'],
        'VI': ['America/Puerto_Rico', 'America/St_Thomas', 'America/Virgin'],
    },
    'Europe': {
        'AL': ['Europe/Tirane'],
        'AT': ['Europe/Vienna'],
        'AX': ['Europe/Mariehamn'],
        'BA': ['Europe/Sarajevo'],
        'BG': ['Europe/Sofia'],
        'BY': ['Europe/Minsk'],
        'CH': ['Europe/Zurich'],
        'CY': ['Europe/Nicosia'],
        'CZ': ['Europe/Prague'],
        'DE': ['Europe/Zurich'],
        'EE': ['Europe/Tallinn'],
        'ES': ['Europe/Madrid'],
        'FR': ['Europe/Paris'],
        'GB': ['Europe/London', 'GB', 'GB-Eire'],
        'GG': ['Europe/Guernsey', 'Europe/London'],
        'HR': ['Europe/Zagreb'],
        'IE': ['Eire'],
        'IM': ['Europe/Isle_of_Man', 'Europe/London'],
        'IT': ['Europe/Rome'],
        'JE': ['Europe/Jersey', 'Europe/London'],
        'LI': ['Europe/Vaduz', 'Europe/Zurich'],
        'LT': ['Europe/Vilnius'],
        'LU': ['Europe/Luxembourg'],
        'LV': ['Europe/Riga'],
        'MC': ['Europe/Monaco', 'Europe/Paris'],
        'MD': ['Europe/Tiraspol'],
        'ME': ['Europe/Podgorica'],
        'MK': ['Europe/Skopje'],
        'MT': ['Europe/Malta'],
        'NO': ['Europe/Oslo'],
        'PL': ['Europe/Warsaw', 'Poland'],
        'PT': ['Europe/Lisbon', 'Portugal'],
        'RU': [
            'Europe/Kaliningrad',
            'Europe/Kirov',
            'Europe/Moscow',
            'Europe/Samara',
            'Europe/Saratov',
            'Europe/Simferopol',
            'Europe/Ulyanovsk',
            'Europe/Volgograd',
            'W-SU',
        ],
        'SE': ['Europe/Stockholm'],
        'SI': ['Europe/Ljubljana'],
        'SJ': ['Arctic/Longyearbyen'],
        'SK': ['Europe/Prague'],
        'SM': ['Europe/Rome', 'Europe/San_Marino'],
        'TR': ['Europe/Istanbul', 'Turkey'],
        'UA': [
            'Europe/Kiev',
            'Europe/Kyiv',
            'Europe/Simferopol',
            'Europe/Uzhgorod',
            'Europe/Zaporozhye',
        ],
        'VA': ['Europe/Rome', 'Europe/Vatican'],
    },
    'Indian': {
        'CC': ['Indian/Cocos'],
        'CX': ['Indian/Christmas'],
        'IO': ['Indian/Chagos'],
        'KM': ['Indian/Comoro'],
        'MG': ['Indian/Antananarivo'],
        'MU': ['Indian/Mauritius'],
        'MV': ['Indian/Maldives'],
        'RE': ['Indian/Reunion'],
        'SC': ['Indian/Mahe'],
        'TF': ['Indian/Kerguelen', 'Indian/Maldives'],
        'YT': ['Indian/Mayotte'],
    },
    'North America': {
        'CA': [
            'America/Atikokan',
            'America/Blanc-Sablon',
            'America/Cambridge_Bay',
            'America/Coral_Harbour',
            'America/Creston',
            'America/Dawson',
            'America/Dawson_Creek',
            'America/Edmonton',
            'America/Fort_Nelson',
            'America/Glace_Bay',
            'America/Goose_Bay',
            'America/Halifax',
            'America/Inuvik',
            'America/Iqaluit',
            'America/Moncton',
            'America/Montreal',
            'America/Nipigon',
            'America/Panama',
            'America/Pangnirtung',
            'America/Phoenix',
            'America/Puerto_Rico',
            'America/Rainy_River',
            'America/Rankin_Inlet',
            'America/Regina',
            'America/Resolute',
            'America/St_Johns',
            'America/Swift_Current',
            'America/Thunder_Bay',
            'America/Toronto',
            'America/Vancouver',
            'America/Whitehorse',
            'America/Winnipeg',
            'America/Yellowknife',
            'Canada/Atlantic',
            'Canada/Central',
            'Canada/Eastern',
            'Canada/Mountain',
            'Canada/Newfoundland',
            'Canada/Pacific',
            'Canada/Saskatchewan',
            'Canada/Yukon',
        ],
        'GL': [
            'America/Danmarkshavn',
            'America/Godthab',
            'America/Nuuk',
            'America/Scoresbysund',
            'America/Thule',
        ],
        'MX': [
            'America/Bahia_Banderas',
            'America/Cancun',
            'America/Chihuahua',
            'America/Ciudad_Juarez',
            'America/Ensenada',
            'America/Hermosillo',
            'America/Matamoros',
            'America/Mazatlan',
            'America/Merida',
            'America/Mexico_City',
            'America/Monterrey',
            'America/Ojinaga',
            'America/Santa_Isabel',
            'America/Tijuana',
            'Mexico/BajaNorte',
            'Mexico/BajaSur',
            'Mexico/General',
        ],
        'PM': ['America/Miquelon'],
        'US': [
            'America/Adak',
            'America/Anchorage',
            'America/Atka',
            'America/Boise',
            'America/Chicago',
            'America/Denver',
            'America/Detroit',
            'America/Fort_Wayne',
            'America/Indiana/Indianapolis',
            'America/Indiana/Knox',
            'America/Indiana/Marengo',
            'America/Indiana/Petersburg',
            'America/Indiana/Tell_City',
            'America/Indiana/Vevay',
            'America/Indiana/Vincennes',
            'America/Indiana/Winamac',
            'America/Indianapolis',
            'America/Juneau',
            'America/Kentucky/Louisville',
            'America/Kentucky/Monticello',
            'America/Knox_IN',
            'America/Los_Angeles',
            'America/Louisville',
            'America/Menominee',
            'America/Metlakatla',
            'America/New_York',
            'America/Nome',
            'America/North_Dakota/Beulah',
            'America/North_Dakota/Center',
            'America/North_Dakota/New_Salem',
            'America/Phoenix',
            'America/Shiprock',
            'America/Sitka',
            'America/Yakutat',
            'Navajo',
            'US/Alaska',
            'US/Aleutian',
            'US/Arizona',
            'US/Central',
            'US/East-Indiana',
            'US/Eastern',
            'US/Indiana-Starke',
            'US/Michigan',
            'US/Mountain',
            'US/Pacific',
        ],
    },
    'Pacific': {
        'AQ': ['Pacific/Auckland', 'Pacific/Port_Moresby'],
        'AS': ['Pacific/Pago_Pago', 'Pacific/Samoa', 'US/Samoa'],
        'CK': ['Pacific/Rarotonga'],
        'CL': ['Chile/EasterIsland', 'Pacific/Easter'],
        'EC': ['Pacific/Galapagos'],
        'FJ': ['Pacific/Fiji'],
        'FM': [
            'Pacific/Chuuk',
            'Pacific/Guadalcanal',
            'Pacific/Kosrae',
            'Pacific/Pohnpei',
            'Pacific/Ponape',
            'Pacific/Port_Moresby',
            'Pacific/Truk',
            'Pacific/Yap',
        ],
        'GU': ['Pacific/Guam'],
        'KI': [
            'Pacific/Enderbury',
            'Pacific/Kanton',
            'Pacific/Kiritimati',
            'Pacific/Tarawa',
        ],
        'MH': ['Kwajalein', 'Pacific/Kwajalein', 'Pacific/Majuro', 'Pacific/Tarawa'],
        'MP': ['Pacific/Guam', 'Pacific/Saipan'],
        'NC': ['Pacific/Noumea'],
        'NF': ['Pacific/Norfolk'],
        'NR': ['Pacific/Nauru'],
        'NU': ['Pacific/Niue'],
        'NZ': ['NZ', 'NZ-CHAT', 'Pacific/Auckland', 'Pacific/Chatham'],
        'PF': ['Pacific/Gambier', 'Pacific/Marquesas', 'Pacific/Tahiti'],
        'PG': ['Pacific/Bougainville', 'Pacific/Port_Moresby'],
        'PN': ['Pacific/Pitcairn'],
        'PW': ['Pacific/Palau'],
        'SB': ['Pacific/Guadalcanal'],
        'TK': ['Pacific/Fakaofo'],
        'TO': ['Pacific/Tongatapu'],
        'TV': ['Pacific/Funafuti', 'Pacific/Tarawa'],
        'UM': [
            'Pacific/Johnston',
            'Pacific/Midway',
            'Pacific/Pago_Pago',
            'Pacific/Tarawa',
            'Pacific/Wake',
        ],
        'US': ['Pacific/Honolulu', 'US/Hawaii'],
        'VU': ['Pacific/Efate'],
        'WF': ['Pacific/Tarawa', 'Pacific/Wallis'],
        'WS': ['Pacific/Apia'],
    },
    'South America': {
        'AR': [
            'America/Argentina/Buenos_Aires',
            'America/Argentina/Catamarca',
            'America/Argentina/ComodRivadavia',
            'America/Argentina/Cordoba',
            'America/Argentina/Jujuy',
            'America/Argentina/La_Rioja',
            'America/Argentina/Mendoza',
            'America/Argentina/Rio_Gallegos',
            'America/Argentina/Salta',
            'America/Argentina/San_Juan',
            'America/Argentina/San_Luis',
            'America/Argentina/Tucuman',
            'America/Argentina/Ushuaia',
            'America/Buenos_Aires',
            'America/Catamarca',
            'America/Cordoba',
            'America/Jujuy',
            'America/Mendoza',
            'America/Rosario',
        ],
        'BO': ['America/La_Paz'],
        'BR': [
            'America/Araguaina',
            'America/Bahia',
            'America/Belem',
            'America/Boa_Vista',
            'America/Campo_Grande',
            'America/Cuiaba',
            'America/Eirunepe',
            'America/Fortaleza',
            'America/Maceio',
            'America/Manaus',
            'America/Noronha',
            'America/Porto_Acre',
            'America/Porto_Velho',
            'America/Recife',
            'America/Rio_Branco',
            'America/Santarem',
            'America/Sao_Paulo',
            'Brazil/Acre',
            'Brazil/DeNoronha',
            'Brazil/East',
            'Brazil/West',
        ],
        'CL': [
            'America/Coyhaique',
            'America/Punta_Arenas',
            'America/Santiago',
            'Chile/Continental',
        ],
        'CO': ['America/Bogota'],
        'EC': ['America/Guayaquil'],
        'GF': ['America/Cayenne'],
        'GY': ['America/Guyana'],
        'PE': ['America/Lima'],
        'PY': ['America/Asuncion'],
        'SR': ['America/Paramaribo'],
        'UY': ['America/Montevideo'],
        'VE': ['America/Caracas'],
    },
}
